version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d0odat0dl3ps73dvcq8g-a.oregon-postgres.render.com/foodsave_db_2
      SPRING_DATASOURCE_USERNAME: behruz
      SPRING_DATASOURCE_PASSWORD: TKJ5YhhOSUPzEsTwkUPeDLRvx6SIoEXq
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    restart: always
